version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.4
    branches:
      only:
        - master
        - /feature/.*
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: Test Code
          command: |
            pipenv run python -m pytest tests/ -vv
      - run:
          name: Validate Questions
          command: |
            pipenv run python -m uploader.question_validator
  deploy:
    docker:
    - image: circleci/python:3.6.4
    branches:
      only:
      - master
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ checksum "Pipfile.lock" }}
        - cache-
    - run:
        name: Install dependencies
        command: pipenv sync --dev
    - save_cache:
        key: cache-{{ checksum "Pipfile.lock" }}
        paths:
        - ~/.local
        - ~/.cache
    - run:
        name: Update Database
        command: |
          pipenv run python -m uploader.question_updater