AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Deploys Slack Quiz Data Tables

Parameters:
  ServiceName:
    Description: The name of the service that you are deploying
    Type: String
    Default: SlackBot
  Stage:
    Description: The Stage/Environment you are building in.
    Type: String
    Default: dev
    AllowedValues:
    - local-dev
    - dev
    - test
    - prod


Resources:
  QuizStorageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: range
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: range
          KeyType: RANGE
      TableName:
        Fn::Sub: ${Stage}-${ServiceName}-storage
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  QuizQuestionsTable:
    Description: The name of the quiz questions table
    Value:
      Ref: QuizStorageTable
    Export:
      Name:
        Fn::Sub: ${Stage}-${ServiceName}-storage